version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  php:
    build:
      context: ./php
    volumes:
      - ./site:/var/www/html:cached
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PHP_FPM_PORT}:9000"
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:stable
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./site:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      php:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
  nginx_logs:
