version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

  php:
    build:
      context: ./php
    volumes:
      - ./site:/var/www/html:cached
    depends_on:
      - db
    ports:
      - "${PHP_FPM_PORT}:9000"

  nginx:
    image: nginx:stable
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./site:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

volumes:
  db_data:
